name: Update Jupyter Books

on:
  workflow_dispatch:
  # push:
  #   branches:
  #   - main


jobs:
  build-book:
    runs-on: ubuntu-latest
    container:
      image: shopjupyterhubacr.azurecr.io/shop/linux/python3.10/vlab:latest
      options: --user root -e GRANT_SUDO=yes
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test notebooks
        run: |
          pip install pytest pytest-xdist nbmake bibtexparser pyyaml Jinja2
          pytest --nbmake -n=auto
      - name: Auto-generate object sections
        run: |
          python render.py
      - name: Build documentation
        run: |
          jupyter book build ./book
      - name: Modify html
        run: |
          python -c 'from scripts import insert_line_in_all_html
          insert_line_in_all_html("./book/_build/html/")'
      - name: Upload to portal
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: shop.sintef.energy
          # server: sintef.sircon.net
          # protocol: ftps
          username: ${{ secrets.SHOP_PORTAL_FTP_USERNAME }}
          password: ${{ secrets.SHOP_PORTAL_FTP_PASSWORD }}
          local-dir: ./book/_build/html/
          server-dir: doc/book/html/
  push-public-repo:
    runs-on: ubuntu-latest
    needs: build-book
    steps:
      - name: Checkout private
        uses: actions/checkout@v3
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install pandas pyyaml Jinja2 bibtexparser
      - name: Push code to public repo
        run: |
          rm -rf .git
          git init
          git config --global user.email "per.aaslid@sintef.no"
          git config --global user.name "Per Aaslid"
          mv -f .publicgitignore .gitignore
          python render.py
          git add -A
          git commit -m "Update doc"
          git remote add public_remote https://${{ secrets.GH_TOKEN_PER }}@github.com/sintef-energy/shop-documentation.git
          git push public_remote master:main --force
