name: Update Jupyter Books

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: shopjupyterhubacr.azurecr.io/shop/linux/python3.9/vlab:latest
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test notebooks
        run: |
          pip install pytest pytest-xdist nbmake
          pytest --nbmake -n=auto
      - name: Build documentation
        run: |
          jupyter book build ./book
      # - name: Upload to portal
      #   uses: SamKirkland/FTP-Deploy-Action@4.3.0
      #   with:
      #     server: shop.sintef.energy
      #     username: ${{ secrets.SHOP_PORTAL_FTP_USERNAME }}
      #     password: ${{ secrets.SHOP_PORTAL_FTP_PASSWORD }}
      #     local-dir: ./book/_build/html/
      #     server-dir: doc/book/html/
