name: Update Jupyter Books

on:
  workflow_dispatch:
  # push:
  #   branches:
  #   - main


jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: shopjupyterhubacr.azurecr.io/shop/linux/python3.10/vlab:latest
      options: --user root -e GRANT_SUDO=yes
      credentials:
        username: ${{ secrets.ACR_USERNAME }}
        password: ${{ secrets.ACR_PASSWORD }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Test notebooks
        run: |
          pip install pytest pytest-xdist nbmake itables
          pytest --nbmake -n=auto
      - name: Auto-generate object sections
        run: |
          python -c "from scripts import *; generate_object_descriptions(); generate_bibliography();"
      - name: Build documentation
        run: |
          jupyter book build ./book
      - name: Modify html
        run: |
          python -c 'from scripts import insert_line_in_all_html
          insert_line_in_all_html("./book/_build/html/")'
      - name: Upload to portal
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: shop.sintef.energy
          # server: sintef.sircon.net
          # protocol: ftps
          username: ${{ secrets.SHOP_PORTAL_FTP_USERNAME }}
          password: ${{ secrets.SHOP_PORTAL_FTP_PASSWORD }}
          local-dir: ./book/_build/html/
          server-dir: doc/book/html/
