name: Publish book to public repo

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout private
        uses: actions/checkout@v3
        with:
          # path: private
          token: ${{ secrets.GH_TOKEN_PER }}
          fetch-depth: 0
      # - name: Checkout public
      #   uses: actions/checkout@v3
      #   with:
      #     repository: sintef-energy/shop-documentation
      #     path: public
      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          python -m pip install pandas pyyaml Jinja2 bibtexparser
      # - uses: oleksiyrudenko/gha-git-credentials@v2.1
      #   with:
      #     global: true
      #     name: 'Per Aaslid'
      #     email: 'per.aaslid@sintef.no'
      #     actor: 'peraaslid'
      #     token: '${{ secrets.GH_TOKEN_PER }}'
      - name: Push code to public repo
        run: |
          # cd $GITHUB_WORKSPACE/doc
          git config --global user.email "per.aaslid@sintef.no"
          git config --global user.name "Per Aaslid"
          git checkout -b public_branch
          rm .gitignore
          mv .publicgitignore .gitignore
          python render.py
          git rm -r --cached .
          git add -A
          git commit -m "Update doc"
          git remote add public_remote https://github.com/sintef-energy/shop-documentation.git
          git push public_remote public_branch:main_test2 --force
