name: Publish book to public repo

on:
  workflow_dispatch:

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - run: |
          git checkout -b public_branch
          rm .gitignore
          mv .publicgitignore .gitignore
          python ./render.py
          git add -A
          git rm -r --cached .
          git commit -m "Update doc"
          git remote add public_remote https://github.com/sintef-energy/shop-documentation.git
      - uses: oleksiyrudenko/gha-git-credentials@v2.1
        with:
          global: true
          name: 'Per Aaslid'
          email: 'per.aaslid@sintef.no'
          actor: 'peraaslid'
          token: '${{ secrets.GH_TOKEN_PER }}'
      - name: Push code to public repo
        run: git push public_remote pubcic_branch:main --force
